font_family JetBrainsMono Nerd Font

foreground              #FFFFFF
background              #131313
selection_foreground    #131313
selection_background    #FFFFFF
cursor                  #9D9D9D
cursor_text_color       #101010

active_tab_foreground     #131313
active_tab_background     #535353
inactive_tab_foreground   #535353
inactive_tab_background   #131313
color0      #1A1A1A
color8      #636363
color1      #FCFCFC
color9      #D6D6D6
color2      #FCFCFC
color10     #D6D6D6
color3      #FCFCFC
color11     #D6D6D6
color4      #B8B8B8
color12     #B8B8B8
color5      #B8B8B8
color13     #B8B8B8
color6      #B8B8B8
color14     #B8B8B8
color7      #FCFCFC
color15     #D6D6D6
