# ==========================================
# IMPORTS (Módulos)
# ==========================================
source = ~/.config/hypr/configs/monitors.conf
source = ~/.config/hypr/configs/programs.conf
source = ~/.config/hypr/configs/autostart.conf
source = ~/.config/hypr/configs/windowrules.conf
source = ~/.config/hypr/configs/keybinds.conf
source = ~/.config/hypr/configs/animations.conf

# ==========================================
# VARIÁVEIS DE AMBIENTE
# ==========================================
env = XCURSOR_SIZE,24
env = HYPRCURSOR_SIZE,24
env = XCURSOR_THEME,Bibata-Modern-Ice

# ==========================================
# LOOK AND FEEL (Tema aplicado)
# ==========================================
general {
    gaps_in = 3
    gaps_out = 3
    border_size = 2

    # Ativo: cinza médio (teu active_tab_background)
    col.active_border = 0xFF535353

    # Inativo: quase preto (teu background/base)
    col.inactive_border = 0xFF1A1A1A

    resize_on_border = false
    allow_tearing = false
    layout = dwindle
}

decoration {
    rounding = 10
    rounding_power = 2

    active_opacity = 1.0
    inactive_opacity = 0.95  # leve diferença pra destacar janela ativa

    shadow {
        enabled = true
        range = 6
        render_power = 3

        # sombra escura baseada no background
        color = rgba(131313ee)
    }

    blur {
        enabled = true
        size = 4
        passes = 2
        vibrancy = 0.1   # mais neutro (menos colorido)
    }
}

dwindle {
    pseudotile = true
    preserve_split = true
}

master {
    new_status = master
}

misc {
    force_default_wallpaper = -1
    disable_hyprland_logo = false
}

# ==========================================
# INPUT
# ==========================================
input {
    kb_layout = br
    follow_mouse = 1
    sensitivity = 0

    touchpad {
        natural_scroll = false
    }
}

device {
    name = epic-mouse-v1
    sensitivity = -0.5
}
