-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- ==========================================

-- IMPORTS (Módulos)

-- ==========================================

require("configs.monitors")
require("configs.programs")
require("configs.autostart")
require("configs.windowrules")
require("configs.keybinds")
require("configs.animations")

-- ==========================================

-- VARIÁVEIS DE AMBIENTE

-- ==========================================

hl.env("XCURSOR_SIZE", 24)

hl.env("XCURSOR_THEME", "McMojave-cursors-dark")

hl.env("HYPRCURSOR_SIZE", 24)

hl.env("HYPRCURSOR_THEME", "McMojave-cursors-dark")

-- ==========================================

-- LOOK AND FEEL (Tema aplicado)

-- ==========================================

hl.config({
    general = {
        gaps_in = 3,
        gaps_out = 3,
        border_size = 1,
        -- Ativo: cinza médio (teu active_tab_background)
        -- Inativo: quase preto (teu background/base)
        resize_on_border = false,
        allow_tearing = false,
        layout = "dwindle",
        col = {
            active_border = "rgba(ffffff33)",
            inactive_border = "rgba(ffffff15)",
        },
    },
})

hl.config({
    decoration = {
        rounding = 10,
        rounding_power = 2,
        active_opacity = 1.0,
        inactive_opacity = 0.95,
        -- leve diferença pra destacar janela ativa
        shadow = {
            enabled = true,
            range = 6,
            render_power = 3,
            -- sombra escura baseada no background
            color = "rgba(131313ee)",
        },
        blur = {
            enabled = true,
            size = 4,
            passes = 2,
            vibrancy = 0.1,
            -- mais neutro (menos colorido)
        },
    },
})

hl.config({
    master = {
        new_status = "master",
    },
})

hl.config({
    misc = {
        force_default_wallpaper = 0,
        disable_hyprland_logo = true,
        mouse_move_enables_dpms = true,
        key_press_enables_dpms = true,
    },
})

-- ==========================================

-- INPUT

-- ==========================================

hl.config({
    input = {
        kb_layout = "br",
        follow_mouse = 1,
        sensitivity = 0,
        touchpad = {
            natural_scroll = false,
        },
    },
})

hl.device({
    name = "epic-mouse-v1",
    sensitivity = -0.5,
})
