-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- Monitor do Notebook (à esquerda)

hl.monitor({
    output   = "eDP-1",
    mode     = "1920x1080@60",
    position = "0x0",
    scale    = 1,
})

-- Monitor Principal (Externo 144Hz, à direita)

hl.monitor({
    output   = "HDMI-A-1",
    mode     = "1920x1080@144",
    position = "1920x0",
    scale    = 1,
})

-- Fallback para outros monitores

hl.monitor({
    output   = "",
    mode     = "preferred",
    position = "auto",
    scale    = 1,
})

-- ==========================================

-- WORKSPACES (Amarrando monitores)

-- ==========================================

hl.workspace_rule({
    workspace = 1,
    monitor = "HDMI-A-1",
    default = true,
})

hl.workspace_rule({
    workspace = 2,
    monitor = "HDMI-A-1",
})

hl.workspace_rule({
    workspace = 3,
    monitor = "HDMI-A-1",
})

hl.workspace_rule({
    workspace = 4,
    monitor = "HDMI-A-1",
})

hl.workspace_rule({
    workspace = 5,
    monitor = "HDMI-A-1",
})

hl.workspace_rule({
    workspace = 6,
    monitor = "eDP-1",
    default = true,
})

hl.workspace_rule({
    workspace = 7,
    monitor = "eDP-1",
})

hl.workspace_rule({
    workspace = 8,
    monitor = "eDP-1",
})

hl.workspace_rule({
    workspace = 9,
    monitor = "eDP-1",
})

hl.workspace_rule({
    workspace = 10,
    monitor = "eDP-1",
})
