exec-once = waybar &
exec-once = nm-applet --indicator &
exec-once = awww-daemon
exec-once = sleep 1 && awww img $HOME/Pictures/Wallpaper/wallpaper_16.png
exec-once = /usr/lib/polkit-kde-authentication-agent-1 &
