exec-once = waybar &
exec-once = nm-applet --indicator &
exec-once = awww-daemon
exec-once = sleep 1 && awww img $HOME/Imagens/Wallpapers/wallpaper_10.jpg
exec-once = /usr/lib/polkit-kde-authentication-agent-1 &
