-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

local browser = "firefox"

local terminal = "kitty"

local fileManager = "nautilus"

local menu = "rofi -show drun"
